services:
    core:
        restart: unless-stopped
        labels:
            traefik.http.routers.core.tls.certresolver: 'letsencrypt'
    pgsql:
        restart: unless-stopped
    rabbitmq:
        restart: unless-stopped
    traefik:
        restart: unless-stopped
        command:
            - '--configFile=/etc/traefik/traefik.yml'
            - '--certificatesresolvers.letsencrypt.acme.email=${ACME_EMAIL}'
    worker:
        build:
            context: './vendor/laravel/sail/runtimes/8.5'
            dockerfile: Dockerfile
            args:
                WWWGROUP: '${WWWGROUP}'
        image: 'sail-8.5/app'
        command: 'php artisan queue:work rabbitmq --tries=3 --backoff=10 --max-time=3600'
        restart: unless-stopped
        environment:
            WWWUSER: '${WWWUSER}'
            LARAVEL_SAIL: 1
        volumes:
            - '.:/var/www/html'
        networks:
            - sail
        depends_on:
            - pgsql
            - rabbitmq
    scheduler:
        build:
            context: './vendor/laravel/sail/runtimes/8.5'
            dockerfile: Dockerfile
            args:
                WWWGROUP: '${WWWGROUP}'
        image: 'sail-8.5/app'
        command: 'php artisan schedule:work'
        restart: unless-stopped
        environment:
            WWWUSER: '${WWWUSER}'
            LARAVEL_SAIL: 1
        volumes:
            - '.:/var/www/html'
        networks:
            - sail
        depends_on:
            - pgsql
